### PR TITLE
Platform-node http client add error event listener in waitForResponse to handle ECONNRESET socket errors

### LINKED ISSUE #328: Platform-node http client not handling ECONNRESET socket errors
I am working with the platform-node implementation of the effect http client and am experiencing an issue where when the remote server closes/destroys the socket (and an ECONNRESET error is thrown) the http request hangs forever. I've created a minimal reproducible example which you can find below. I think this behavior is a bug and would be willing to submit a PR but I am still quite slow at debugging this library so any help/pointers would be appreciated. If you don't think this is a bug, could you explain why this is desired and how I might be able to avoid it?

```ts
import * as NodeHttp from "@effect/platform-node/HttpClient";
import { Effect } from "effect";
import http from "node:http";

// Dummy http server that forcefully close the connection with an ECONNRESET error every time
http.createServer((request) => {
    request.socket.destroy();
}).listen(5000);

// Node.js request correctly handles this
const testRequest = (url: string) =>
    new Promise((resolve, reject) => {
        const request = http.request(url, (response) => {
            const data: string[] = [];
            response.on("data", (chunk) => {
                data.push(chunk);
            });
            response.on("end", () => {
                resolve(data.join(""));
            });
            response.on("error", (error) => {
                reject(error);
            });
        });
        request.end();
        request.on("error", (error) => {
            reject(error);
        });
    });

// <!doctype html>
// <html>
// <head>
//     <title>Example Domain</title>
// ...
await testRequest("http://example.com").then(console.log);

// Error: socket hang up
//     at connResetException (node:internal/errors:787:14)
//     at Socket.socketOnEnd (node:_http_client:519:23)
//     at Socket.emit (node:events:526:35)
//     at endReadableNT (node:internal/streams/readable:1589:12)
//     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
//   code: 'ECONNRESET'
// }
await testRequest("http://localhost:5000/_ping").catch(console.error);

// HANGS FOREVER!!
// If I add a console.log(error) before the resume call on this line: https://github.com/Effect-TS/platform/blob/0f19070a9fc9d2f3faa7c0191c47af65ccfcfece/packages/platform-node/src/internal/http/nodeClient.ts#L157
// I can see this error message
// Error: socket hang up
//     at connResetException (node:internal/errors:787:14)
//     at Socket.socketOnEnd (node:_http_client:519:23)
//     at Socket.emit (node:events:526:35)
//     at endReadableNT (node:internal/streams/readable:1589:12)
//     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
//   code: 'ECONNRESET'
// }
// But it never bubbles up?
// So this effect hangs forever
const result = await Effect.gen(function* (_: Effect.Adapter) {
    const client: NodeHttp.client.Client.Default = yield* _(NodeHttp.nodeClient.make);

    const response: string = yield* _(
        NodeHttp.request
            .make("GET")("/")
            .pipe(NodeHttp.request.prependUrl("http://localhost:5000"))
            .pipe(client.pipe(NodeHttp.client.filterStatusOk))
            .pipe(Effect.flatMap((response) => response.text))
    );

    return response;
})
    .pipe(Effect.orDie)
    .pipe(Effect.provide(NodeHttp.nodeClient.agentLayer))
    .pipe(Effect.runPromise);

console.log(result);
```

```json
"dependencies": {
    "effect": "2.0.0-next.59",
    "@effect/platform-node": "0.34.0"
}
```

oh and node v20.10.0

### PR DESCRIPTION
**Pull request by leonitousconforti**
fixes #328

### CODE REVIEW

File: packages/platform-node/src/internal/http/nodeClient.ts [hunk 1]
```diff
@@ -141,12 +141,22 @@ const sendBody = (
     }
   })
 
-const waitForResponse = (nodeRequest: Http.ClientRequest) =>
+const waitForResponse = (nodeRequest: Http.ClientRequest, request: ClientRequest.ClientRequest) =>
   Effect.async<never, never, Http.IncomingMessage>((resume) => {
```
Comment (tim-smart) [inline packages/platform-node/src/internal/http/nodeClient.ts:145]: Need to set the error type here :)

**Review by tim-smart — CHANGES_REQUESTED** [review]

**Comment by tim-smart** [comment]
Thanks!
